Repository github/gh-ost, pull requests merged in 2021-05, with the labels that each got.

#962 fix #961
  go/logic/inspect.go
Labels: bug, low-risk, needs-testing

#954 Remove build_id files from rpm
  build.sh
Labels: low-risk

#921 Cut-over should wait for heartbeat lag to be low enough to succeed
  doc/hooks.md
  go/base/context.go
  go/logic/hooks.go
  go/logic/migrator.go
Labels: bug, enhancement, needs-testing

#968 Use matrix build for replica test CI
  .github/workflows/replica-tests.yml
  script/cibuild-gh-ost-replica-tests
Labels: build, low-risk

#970 Use GitHub Actions CI badges
  README.md
Labels: documentation, enhancement

#919 Generated column as part of UNIQUE (or PRIMARY) KEY
  go/logic/inspect.go
  localtests/generated-columns57-unique/create.sql
  localtests/generated-columns57-unique/ignore_versions
Labels: enhancement, needs-testing

#966 Add GO111MODULE=off to build.sh, use Golang 1.16
  .github/workflows/ci.yml
  .github/workflows/replica-tests.yml
  Dockerfile.packaging
  Dockerfile.test
  README.md
  build.sh
  localtests/test.sh
  script/build
  script/ensure-go-installed
  script/test
  test.sh
Labels: build, enhancement, low-risk

#931 All MySQL DBs limited to max 3 concurrent/idle connections #15
  go/logic/throttler.go
  go/mysql/utils.go
Labels: enhancement, low-risk
