Repository github/gh-ost, pull requests merged in 2022-07, with the labels that each got.

#1140 Fix `integer divide by zero` panic in migrator
  go/logic/migrator.go
Labels: low-risk

#387 compound pk tests
  localtests/compound-pk-ts/create.sql
  localtests/compound-pk/create.sql
  localtests/test.sh
Labels: enhancement, build, low-risk

#1132 Ensure mysql rows responses are closed
  .golangci.yml
  go/logic/applier.go
Labels: enhancement

#1135 Use `switch` statements for readability, simplify `.NewGoMySQLReader()`
  go/binlog/gomysql_reader.go
  go/logic/migrator.go
  go/logic/streamer.go
Labels: enhancement, low-risk

#1131 Add context/timeout to HTTP throttle check
  .golangci.yml
  go/base/context.go
  go/cmd/gh-ost/main.go
  go/logic/migrator.go
  go/logic/throttler.go
Labels: enhancement

#1136 Default to `go1.17.11`
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/replica-tests.yml
  Dockerfile.packaging
  Dockerfile.test
  go.mod
  script/ensure-go-installed
  vendor/github.com/go-sql-driver/mysql/go.mod
  vendor/github.com/pingcap/errors/go.mod
  vendor/github.com/pingcap/errors/go.sum
  vendor/go.uber.org/atomic/go.mod
  vendor/go.uber.org/atomic/go.sum
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/modules.txt
Labels: build, low-risk

#846 Cancel any row count queries before attempting to cut over
  go/base/context.go
  go/logic/inspect.go
  go/logic/migrator.go
Labels: bug, enhancement, needs-testing

#1138 Changlog table comment
  go/logic/applier.go
Labels: enhancement, low-risk

#1145 `golang-ci`: enable/fix `staticcheck` lint warnings
  .golangci.yml
  go/base/context.go
  go/base/utils.go
  go/cmd/gh-ost/main.go
  go/logic/applier.go
  go/logic/migrator.go
  go/logic/server.go
  go/logic/streamer.go
  go/logic/throttler.go
  go/sql/builder.go
Labels: enhancement, low-risk

#1134 Add `Migrated` changelog event state
  go/logic/migrator.go
Labels: enhancement, needs-testing

#1147 Remove unused `go/os/process.go`
  go/os/process.go
Labels: enhancement, low-risk

#1148 Move `.Kill()` func from inspector to `go/mysql`
  go/logic/inspect.go
  go/mysql/utils.go
Labels: enhancement, low-risk

#1151 Add script and docs for linter
  .golangci.yml
  doc/coding-ghost.md
  script/ensure-golangci-lint-installed
  script/lint
Labels: enhancement, documentation, build, low-risk

#1149 Enable more `golang-ci` linters
  .golangci.yml
  go/cmd/gh-ost/main.go
  go/logic/applier.go
  go/logic/migrator.go
  go/logic/server.go
  go/logic/streamer.go
  go/logic/throttler.go
  go/mysql/instance_key.go
  go/sql/builder.go
  go/sql/parser.go
  go/sql/parser_test.go
Labels: enhancement, low-risk
