Repository github/gh-ost, pull requests merged in 2023-12, with the labels that each got.

#1331 fix: typo
  doc/azure.md
Labels: documentation, low-risk

#1349 Remove stale `RELEASE_VERSION` file
  RELEASE_VERSION
  build.sh
Labels: build, low-risk

#1347 Include git commit in version
  build.sh
  go/cmd/gh-ost/main.go
Labels: build, low-risk

#1226 Fix tokens in inspector logging
  go/logic/inspect.go
Labels: bug, low-risk

#1246 Cleanup whitespace and comments in SQL query text
  go/logic/applier.go
  go/logic/applier_test.go
  go/logic/inspect.go
  go/sql/builder.go
  go/sql/builder_test.go
Labels: enhancement, low-risk

#1352 Fix `--version` output
  go/cmd/gh-ost/main.go
Labels: build, low-risk

#1351 Update to `go1.21`
  .github/workflows/ci.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/replica-tests.yml
  Dockerfile.packaging
  Dockerfile.test
  go.mod
  go.sum
  go/base/context_test.go
  go/base/load_map.go
  go/base/utils.go
  go/mysql/connection.go
  script/build-deploy-tarball
  script/ensure-go-installed
  script/ensure-golangci-lint-installed
Labels: needs-testing, build

#1354 Replace deprecated `github.com/satori/go.uuid` lib
  go.mod
  go.sum
  go/base/context.go
  vendor/github.com/google/uuid/CHANGELOG.md
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/null.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/modules.txt
Labels: low-risk

#1350 Add `CODEOWNERS` file to auto-request reviews
  .github/CODEOWNERS
Labels: build, low-risk
